version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # Database service
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: eluma
      POSTGRES_PASSWORD: ppp
      POSTGRES_DB: posgre
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
